name: Upload to Smartcat

on:
  push:
    paths:
      - 'localization/**'

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install requests
        run: pip install requests

      - name: Run upload script
        run: |
          python .github/scripts/upload_to_smartcat.py
        env:
          SMARTCAT_API_KEY: ${{ secrets.SMART_API_KEY }}
          SMARTCAT_PROJECT_ID: ${{ secrets.SMARTCAT_PROJECT_ID }}
